### PR TITLE
Added Classes/Commands

### PR DESCRIPTION
**Pull request by cturvey**
Cleaned the alpha-sort order somewhat so I can more easily diff my own lists
Filled out the Classes
Filled out and added Public Commands

### CODE REVIEW

**Comment by PaulZC** [comment]
Many thanks Clive (@cturvey ),

Sadly, my lists follow the alphabetical order of the interface description...

I'll merge this into release_candidate and let it lie for a few days, just in case you add more improvements! ;-) (Saleae review and approve any new releases before including them in the marketplace.)

Thanks again,
Paul

**Comment by PaulZC** [comment]
I'm changing DBG from 0x0d to 0x0c

**Comment by PaulZC** [comment]
@cturvey : Done. Please pull the release_candidate branch and let me know if I missed anything. Thanks!

**Comment by cturvey** [comment]
I see

Yeah, I will probably fiddle with it more. Might attempt adding packet decodes, but will try those one at a time.

**Pull request merged**
