### PR TITLE
Add support for decoding MON-HW, NAV-STATUS and NAV-TIMEGPS messages

### PR DESCRIPTION
**Pull request by maehw**
…(according to u-blox 6 Protocol Specification)

**Thanks for providing the code base.**

I tried to adapt the code style and added support for three message types.

I increased version number to v1.0.2, but feel free to make modifications.

---

**Background:**

Use case: troubleshooting/understanding communication between [OpenBikeSensor](https://www.openbikesensor.org/)'s GPS module u-blox NEO-6 and its ESP32 MCU.

See also: [German wiki article](https://forum.openbikesensor.org/t/wiki-gps-troubleshooting-fehlersuche/170) in the OBS project

A project that might be of interest for you: https://github.com/maehw/ubx-gps-simulator

### CODE REVIEW

**Comment by PaulZC** [comment]
Hi @maehw ,

Thank you for submitting this pull request. I am glad you are finding the analyzer useful!

I will review this next week.

Best wishes,
Paul

**Comment by maehw** [comment]
Hi Paul,

thank you.

I used the time being on a train to add some more refactoring (no functional changes).

From the commit message:

> **Refactoring: modify code style to throw less warnings in PyCharm, comply more with PEP 8**
> 
> - PEP 8: E221 multiple spaces before operator
> - PEP 8: E231 missing whitespace after ','
> - PEP 8: E265 block comment should start with '# '
> - PEP 8: E261 at least two spaces before inline comment
> - PEP 8: E302 expected 2 blank lines, found 1
> - PEP 8: E501 line too long (> 120 characters)
> - PEP 8: E701 multiple statements on one line (colon)
> - Local variable 'char' value is not used
> - Triple double-quoted strings should be used for docstrings.
> - Shadowing of built-in name 'format'
> - Instance attribute <attribute name> defined outside __init__
> - Removal of redundant parentheses
> - Fix comparison with None performed with equality operators
> - Function name should be lowercase

**Comment by PaulZC** [comment]
Hi @maehw ,

Thank you again for submitting this Pull Request.

I have two suggestions / corrections:

1) MON-HW M6 vs M8

On M8 modules, MON-HW is 60 bytes, instead of 68. Only 17 pin mappings (VP) are used; and cwSuppression replaces jamInd:

image

It would be great if the analyzer could distinguish between the two. You could use the two length bytes to indicate which is which. Is this something you could add?

2) VP formatting

VP is a 25-byte array which is currently being printed as a 200-bit hex number... I don't think that is the best approach. Also, the data is 'reversed' (LS Byte first) and I do not know if that matches the pin numbering order?

Perhaps you could add a new 'hex_array' format - to complement 'hex' and 'dec'? Perhaps using %02X format, separated by spaces?

Thank you - and best wishes,
Paul

**Comment by maehw** [comment]
Hi Paul,

sure, this is totally feasible. Unfortunately, I won't have time in the next two-three weeks.

I'll come back to this later. If you don't hear back from me in about a month, feel free to remind me.

Thanks & bye!

**Comment by maehw** [comment]
I've just added some more decoding support - considering both M6 and M8 specifications.
Haven't really fixed the review comments yet.

**Comment by maehw** [comment]
Hi @PaulZC ,

coming back to your review remarks:

Instead of implicitly trying to distinguish between M6 and M8 modules by some message lengths - what do you think about explicitly selecting selecting M6 or M8 module from the decoder's settings menu as a drop-down menu?

This would also allow to decode same-length messages where the payload bytes are used (or field names are called) different in M6 and M8 modules?

I could then walk through all currently implemented messages and check for differences.

maehw

**Comment by PaulZC** [comment]
Hello @maehw ,

Thank you again for the contribution

I think an M6/M8 drop-down is a great idea. Let's add that.

Also, I am going to start adding support for NMEA and RTCM. It will not be as complete as UBX, just basic length and checksum-checking, but I think many users will find it useful.

I am going to merge your changes as-is into the **release_candidate** branch - and then start adding NMEA and RTCM.

Best wishes,
Paul

**Comment by PaulZC** [comment]
Just for information, my priorities are:

* Add NMEA
* Add RTCM
* Add support for SPI

If time permits, I will also look at:

* The _array_ type
* The M6/M8 selection

**Comment by PaulZC** [comment]
Hi @maehw ,

OK. The NMEA and RTCM parsing is working. I also added ```analyze_array``` and changed MON-HW so it uses that for the VP analysis. I think it is an improvement - but let me know what you think.

I didn't have time to add SPI. I will try to do that tomorrow / Monday.

Please do add the M6 / M8 switch - if you have time. That will be a really nice feature.

Please use the [release_candidate](https://github.com/sparkfun/SparkFun_u-blox_UBX_HLA/tree/release_candidate) branch for your new changes - thanks!

Best,
Paul

**Comment by PaulZC** [comment]
Hello @maehw ,

I added SPI support and the M8/M6 selection. I updated MON-HW so it uses the correct number of pins for M6 and M8. I also added NAV-POSECEF and NAV-POSLLH (they are the same on the M6 and M8).

Please test the new version in the [release_candidate](https://github.com/sparkfun/SparkFun_u-blox_UBX_HLA/tree/release_candidate) branch. If you think it is OK, I will merge and release it.

Best wishes,
Paul

**Comment by PaulZC** [comment]
Hello @maehw ,

I need to work on other projects, so I have released v1.0.2 today. Please test it when you have time.

Best wishes,
Paul

**Comment by maehw** [comment]
Hi @PaulZC,

thank you for your support. Sorry, I've also different projects going on and sometimes it takes several weeks until I can come back to the same one.

maehw

**Comment by PaulZC** [comment]
Hi @maehw ,

No problem!

I am very happy with version 1.0.2. The I2C address selection is working well. It means I can add two analyzers: one on address 66 (0x42) to monitor a ZED-F9P; a second on address 67 (0x43) to monitor a NEO-D9S on the same bus.

Thanks again for the contribution.

Very best wishes,
Paul

**Pull request merged**
